Migrate raw sql scripts into initializer format
palladiumkenya/kenyahmis pull request #5
Opened 2024-01-09 10:44 UTC by jecihjoy

2024-01-09 16:43 UTC, ibacher requested changes
Nice work @jecihjoy! This mostly looks good, but a few things need to be fixed for this to work properly and a few suggestions for how things can be simplified.

2024-01-09 16:43 UTC, ibacher commented on configs/openmrs/initializer_config/conceptsources/conceptsources-core_data.csv
> +UUID,Void/Retire,Name,Description,HL7 Code,Unique ID
So, this project inherits from the Ozone project which inherits the configuration from the RefApp. There's an override [in this project](https://github.com/palladiumkenya/kenyahmis/blob/126a2e6308e76b24bf5c0300e05823fbaadaa650/pom.xml#L159) which excludes _some_ of the RefApp metadata, but shouldn't exclude this or the `fhirconceptsources` domain, so unless you have specific customizations for those, you shouldn't need to include those files in the package.

I think I probably made in mistake in telling you to point the Validator at `${project.basedir}/configs/openmrs/initializer_config`; it should actually point at `${project.build.directory}/${project.artifactId}-${project.version}/distro/configs/openmrs/initializer_config`. (We're working to simplify the process of setting up Ozone distributions; see [here](https://github.com/ozone-his/ozone-distro/pull/32) for a glimpse of where this is headed).

2024-01-09 16:43 UTC, ibacher commented on configs/openmrs/initializer_config/liquibase/liquibase.xml
> +	<changeSet id="load_all_concepts_${project.version}" author="jecihjoy">
For this to work, it needs to be run through Maven filtering. To do that we need to modify the executions of the maven-resource-plugin [here](https://github.com/palladiumkenya/kenyahmis/blob/126a2e6308e76b24bf5c0300e05823fbaadaa650/pom.xml#L124) to something like:

```xml
<execution>
  <!-- Override with local config files-->
  <id>Copy local resources</id>
  <phase>process-resources</phase>
  <goals>
    <goal>copy-resources</goal>
  </goals>
  <configuration>
    <outputDirectory>
      ${project.build.directory}/${project.artifactId}-${project.version}/distro/configs</outputDirectory>
    <overwrite>true</overwrite>
    <resources>
      <resource>
        <directory>${project.parent.basedir}/configs</directory>
        <excludes>
          <exclude>.gitkeep</exclude>
          <exclude>openmrs/initializer_config/liquibase/liquibase.xml</exclude>
        </excludes>
      </resource>
    </resources>
  </configuration>
</execution>
<execution>
  <!-- Override with filtered local config files-->
  <id>Copy local resources with filtering</id>
  <phase>process-resources</phase>
  <goals>
    <goal>copy-resources</goal>
  </goals>
  <configuration>
    <outputDirectory>
      ${project.build.directory}/${project.artifactId}-${project.version}/distro/configs</outputDirectory>
    <overwrite>true</overwrite>
    <resources>
      <resource>
        <directory>${project.parent.basedir}/configs</directory>
        <includes>
          <include>openmrs/initializer_config/liquibase/liquibase.xml</include>
        </includes>
      </resource>
    </resources>
    <filtering>true</filtering>
  </configuration>
</execution>
```

Without this change, you'll end up with a Liquibase change with the `id` `load_all_concepts_${project.version}`. With this change, that'll be `load_all_concepts_1.0.0-SNAPSHOT`

2024-01-09 16:43 UTC, ibacher commented on configs/openmrs/initializer_config/conceptsources/conceptsources-core_data.csv
> +UUID,Void/Retire,Name,Description,HL7 Code,Unique ID
If the excludes exclude files that should be included, please feel free to modify them.

2024-01-09 16:43 UTC, ibacher commented on configs/openmrs/initializer_config/liquibase/liquibase.xml
> +	xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog/1.9 http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-1.9.xsd">
I mentioned this on Slack, but for completeness:

```suggestion
<databaseChangeLog xmlns="http://www.liquibase.org/xml/ns/dbchangelog/2.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog/2.0 http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-2.0.xsd">
```

2024-01-10 22:54 UTC, jecihjoy commented
@ibacher I have adress your reviews above. However when testing locally I ran into this [error](https://pastebin.com/y5tzaKZC) when liquibase changes was executing 
Initially I thought initializer was referenceing methods in latest openmrs version `2.7.0-SNAPSHOT` I tested against said version and still ran into the same error.

2024-01-11 13:38 UTC, ibacher commented on configs/openmrs/initializer_config/liquibase/liquibase.xml
> +			path="drug/truncate_drugs-10-25.sql" />
@jecihjoy At a first guess, the problem causing the current error you reported is this line.

2024-01-18 14:24 UTC, ibacher commented on pom.xml
> +                  <includes>
The problem here, and the reason I suggested having two executions, is that this will now _only_ copy the `liquibase/liquibase.xml` and not the rest of the configurations.

2024-01-31 16:35 UTC, ibacher approved these changes

2024-01-31 16:53 UTC, jecihjoy commented
Finally we can merge this. Thank you Ian for your guidance

2024-01-31 16:53 UTC, merged

2024-01-31 16:53 UTC, ibacher commented
So glad we got this finished!